### ISSUE TITLE
3-Authorization/1-call-api: Web Call API blocked by CORS

### ISSUE THREAD

**Issue by pjchungmd** [Azure-Samples/ms-identity-javascript-tutorial#12]
# Issue

> After following the instructions in the 3-Authorization/1-call-api tutorial code, and running the app on localhost, I am able to sign in, but when pressing the "Call API" button, I only see "Calling Web API" and receive the following message on the console:

`Access to fetch at 'http://localhost:5000/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

In `index.js` I have not removed:

    // enable CORS (for testing only -remove in production/deployment)
    app.use((req, res, next) => {
        res.header("Access-Control-Allow-Origin", "*");
        res.header("Access-Control-Allow-Headers", "Authorization, Origin, X-Requested-With, Content-Type, Accept");
        next();
    });

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [x ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Call a web API that calls Microsoft Graph on-behalf-of user
    - [ ] 4-2) Call a web API that calls another web API on-behalf-of user
    - [ ]   5) Deploy to Azure Storage and App Service
```

## This issue is for a

```console
    - [x ] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

>Followed all steps in the tutorial and when clicking on the button receive the above error.

### Any log messages given by the failure

> Access to fetch at 'http://localhost:5000/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

### Expected/desired behavior

> Expect to see "Web API responded: Hello <my name>!"

### Library version

> As provided in the git repository

### Browser and version

> Chrome (Version 88.0.4324.104), Edge (Version 88.0.705.56)

Thanks! We'll be in touch soon.

**Comment by pjchungmd** [comment]
I found the answer:

At the bottom of the instructions it says:

> After you configured your web API, open the App\apiConfig.js file. Then:

> Find the key Enter_the_Web_Api_Uri_Here and replace the existing value with the coordinates of your web API (by default http://localhost:5000).

> Find the key Enter_the_Web_Api_Scope_Here and replace the existing value with the scopes for your web API, like api://e767d418-b80b-4568-9754-557f40697fc5/access_as_user. You can copy this from the Expose an API blade of the web APIs registration.

I followed this, but the code had the correct hint which was to put in `http://localhost:5000/api`. Replacing this solved the problem.

**Comment by derisen** [comment]
@pjchungmd thank you very much for taking time and creating a detailed issue. And congrats on figuring it out! Yeah that seems to be a mistake. Feel free to make a PR to correct that, otherwise I'll fix that asap.
