### ISSUE TITLE
Issue with Microsoft Graph on-behalf-of user

### ISSUE THREAD

**Issue by pra7eek** [Azure-Samples/ms-identity-javascript-tutorial#16]
# Issue

> Please provide us with the following information:

Following code
```javascript
myMSALObj.loginPopup(loginRequest)
        .then(handleResponse)
        .catch(error => {
            console.error(error);
        });
```
throws error 
```
ServerError: invalid_client: 7000218 - [2021-04-19 18:09:38Z]: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: <trace-id>
```

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [ ] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [x] 4-1) Call a web API that calls Microsoft Graph on-behalf-of user
    - [ ] 4-2) Call a web API that calls another web API on-behalf-of user
    - [ ]   5) Deploy to Azure Storage and App Service
```

## This issue is for a

```console
    - [x] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

>

### Any log messages given by the failure

>

### Expected/desired behavior

>

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@pra7eek can you share the your configuration? (masking client secret, if any). In particular, double check to make sure your SPA redirect URI is registered as **Single page application** (on **Authentication** blade):

![screenshot](https://user-images.githubusercontent.com/13197548/115295850-1131f480-a10f-11eb-9f0a-27a195a5a6d1.png)
![screenshot](https://user-images.githubusercontent.com/13197548/115295858-13944e80-a10f-11eb-9c08-640e5c9eadec.png)

**Comment by pra7eek** [comment]
Hi @derisen , thanks for the response. When I added the Redirect URI while creating the app, by default it was assigned to the 'Web' type of application. After seeing your screenshot I changed it to the SPA app, and now I'm able to run the example.

**Comment by derisen** [comment]
@pra7eek cheers! Closing this.
