### ISSUE TITLE
Use AuthCodeMSALBrowserAuthenticationProvider from Graph JS library

### ISSUE THREAD

**Issue by nikithauc** [Azure-Samples/ms-identity-javascript-tutorial#21]
The MS Graph JS SDK 3.0.0 will introduce the `AuthCodeMSALBrowserAuthenticationProvider`  supporting the `msal-browser` library.  The samples in this repository make use of a Custom MSALAuthenticationProvider which can be now replaced by `AuthCodeMSALBrowserAuthenticationProvider`.

This feautures is available in preview -> https://www.npmjs.com/package/@microsoft/microsoft-graph-client/v/3.0.0-Preview.3

**Comment by derisen** [comment]
@nikithauc great news! I'll keep the custom MSALAuthenticationProvider approach as reference, and add the new AuthCodeMSALBrowserAuthenticationProvider as well. Will close this issue once the PR is merged.
