### ISSUE TITLE
Strategy.prototype.jwtVerify: cannot verify token

### ISSUE THREAD

**Issue by NamedArray** [Azure-Samples/ms-identity-javascript-tutorial#23]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [X] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Call a web API that calls Microsoft Graph on-behalf-of user
    - [ ] 4-2) Call a web API that calls another web API on-behalf-of user
    - [ ]   5) Deploy to Azure Storage and App Service
```

## This issue is for a

```console
    - [X] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

I followed everything to the letter --- so I've got the SPA and API registered and running.  However, the API is not working correctly.

I was able to see the token and parse it at jst.ms (snippet below)

The SPA frontend is getting an Unauthorized error when it tries to go through the API.  Console output from the API says the following:

`"msg":  "authentication failed due to: In Strategy.prototype.jwtVerify: cannot verify token"`

The AUD (AUDIENCE) token looks incorrect to me:

<html>
<body>

Claim type | Value | Notes
-- | -- | --
aud | 00000003-0000-0000-c000-000000000000 | Identifies the intended recipient of the token. In id_tokens, the audience is your app's Application ID, assigned to your app in the Azure portal. Your app should validate this value, and reject the token if the value does not match.

</body>
</html>

**Comment by derisen** [comment]
@NamedArray from the `aud` claim it looks like this is a token for Microsoft Graph, not for your web API. So that's why verification fails. Somehow you are sending the wrong access token to your API. Have you made any changes to the code [here](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/blob/dc699fca6e038434c742532787c4fd33d966825f/3-Authorization-II/1-call-api/SPA/App/authConfig.js#L19) or [here](https://github.com/Azure-Samples/ms-identity-javascript-tutorial/blob/dc699fca6e038434c742532787c4fd33d966825f/3-Authorization-II/1-call-api/SPA/App/authPopup.js#L101)?

**Comment by NamedArray** [comment]
@derisen Yes....

Though, I did not make any changes to your 2nd reference:  `function passTokenToApi()`

The XXXX reference below is the CLIENT ID of the API I wish to call.

I tried omitting the GUID, and using "access_as_user" only, but that had no affect.

I also made sure "\v2" was being listed correctly in the config (another article mentioned that missing "\v2" can sometimes be a problem)

Another thing I noticed was that GraphAPI "user.read" permissions were automatically added.


```
// Add here the endpoints and scopes for the web API you would like to use.
const apiConfig = {
    uri: "http://localhost:5000/api", // e.g. http://localhost:5000/api
    scopes: ["api://cad2ce6d-XXXX-XXXX-XXXX-XXXXXX781b50/access_as_user"] // e.g. ["scp1", "scp2"]
};
```

**Comment by derisen** [comment]
@NamedArray Ok I see. So MSAL.js adds `openid`, `profile `and `User.Read` scopes by default to `loginPopup`/`loginRedirect` methods. When the user first signs-in, they get an access token with these scopes. This access token is meant for Microsoft Graph API [userinfo endpoint](https://docs.microsoft.com/en-us/azure/active-directory/develop/userinfo). So this is **not** the access token you want to send.

It looks like your `apiConfig ` object is correctly set up, so I'm guessing the right token is sent to the API. The issue then must be about the token version. By default Azure picks v1 tokens, but our web API here is set to validate v2 tokens. Can you confirm that, for your web API's registration on Azure portal, you carried out this step:

> On the right side menu, select the **Manifest** blade.
> Set **accessTokenAcceptedVersion** property to **2**.
> Click on **Save**.

**Comment by NamedArray** [comment]
Okay, so I restarted from scratch, following everything again line-by-line.  I'm still getting the 'Unauthorized' response from the API.

Node console:  `{"name":"AzureAD: Bearer Strategy","hostname":"REDACTED","pid":4680,"level":30,"msg":"authentication failed due to: In Strategy.prototype.jwtVerify: cannot verify token","time":"2021-09-08T15:39:44.479Z","v":0}

I have verified that the manifest has `accessTokenAcceptedverions: 2`

When I use [jwt.ms](https://jwt.ms/) to parse the token.... which one am I supposed to be using from the browser's console.log?  `accessToken:` or `idToken`?

Under the API, on line 11 under `index.js`, when I map out the options for `identityMetadata` and `issuer`, it would look like this (below).  Does this look right to you?

```
// index.js, line 11, API, 

const options = {
    identityMetadata: https://login.microsoftonline.com/<my tenant GUID>/v2.0/.well-known/openid-configuration
    issuer: https://login.microsoftonline.com/<my tenant GUID>/v2.0
    ...
};
```

**Comment by derisen** [comment]
> Okay, so I restarted from scratch, following everything again line-by-line. I'm still getting the 'Unauthorized' response from the API.
> 
> Node console: `{"name":"AzureAD: Bearer Strategy","hostname":"REDACTED","pid":4680,"level":30,"msg":"authentication failed due to: In Strategy.prototype.jwtVerify: cannot verify token","time":"2021-09-08T15:39:44.479Z","v":0}`
> 
> I have verified that the manifest has `accessTokenAcceptedverions: 2`
> 
> When I use [jwt.ms](https://jwt.ms/) to parse the token.... which one am I supposed to be using from the browser's console.log? `accessToken:` or `idToken`?

@NamedArray you should use access token on `jwt.ms`. The ID token is only meant for your client app. It's the access token that needs to be sent to your web API, with the `aud `claim being your API's client Id and `scp `claim should be `access_as_user`

> Under the API, on line 11 under `index.js`, when I map out the options for `identityMetadata` and `issuer`, it would look like this (below). Does this look right to you?
> 
> ```
> // index.js, line 11, API, 
> 
> const options = {
>     identityMetadata: https://login.microsoftonline.com/<my tenant GUID>/v2.0/.well-known/openid-configuration
>     issuer: https://login.microsoftonline.com/<my tenant GUID>/v2.0
>     ...
> };
> ```

This looks correct to me. So it's strange... Can you send me a network trace using [Fiddler](https://www.telerik.com/fiddler)? My email is on my GitHub profile.

**Comment by NamedArray** [comment]
@derisen Oh man, I really want to comply with your request.  I installed Fiddler Classic, but I can't figure out how to get it to work... It's not capturing _anything_.  I think our Network Team has it blocked somehow (even though the Node Apps are on localhost:3000 & 5000). I can't seem to find an extension on the Chrome store either (Fiddler Jam?).  Do you know how to configure Fiddler properly?

I know how to use Postman...  is there anything I can generate from that?  

Also, your email address is a gmail suffix.... just want to make sure you're really a Microsoft Employee :)

**Comment by derisen** [comment]
> @derisen Oh man, I really want to comply with your request. I installed Fiddler Classic, but I can't figure out how to get it to work... It's not capturing _anything_. I think our Network Team has it blocked somehow (even though the Node Apps are on localhost:3000 & 5000). I can't seem to find an extension on the Chrome store either (Fiddler Jam?). Do you know how to configure Fiddler properly?

Did you check their [training video](https://www.youtube.com/watch?v=gujBKFGwjd4)? Might help. If the corporate network is the issue, maybe you can give this a try when you're home? :)

> I know how to use Postman... is there anything I can generate from that?
> 
> Also, your email address is a gmail suffix.... just want to make sure you're really a Microsoft Employee :)

Haha fair : ) I don't use work mail here (cuz spams etc.) but you can see on my profile I'm part of Microsoft and Azure AD organizations.

**Comment by NamedArray** [comment]
@derisen I just sent an email.  I suppose, since we've taken this _offline_, we can close this issue, unless of course there's a fix that ends up being beneficial to everyone else?

**Comment by NamedArray** [comment]
OK, whoever finds this in the future, for this example `3-Authorization-II/1-call-api`, in the `config.json` file, make sure that `clientID` is the same as `audience`.

Somehow, I missed step 4  `Configure the service app to use your app registration`:

> 4. Find the key audience and replace the existing value with the application ID (clientId) of the ms-identity-javascript-tutorial-c3s1-api application copied from the Azure portal.

Thanks @derisen !!! :)
