### ISSUE TITLE
Json format error

### ISSUE THREAD

**Issue by sl7xman** [Azure-Samples/ms-identity-javascript-tutorial#34]
# Issue

> Please provide us with the following information:

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [x] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [x] 4-1) Call a web API that calls Microsoft Graph on-behalf-of user
    - [x] 4-2) Call a web API that calls another web API on-behalf-of user
    - [ ]   5) Deploy to Azure Storage and App Service
```

## This issue is for a

```console
    - [x] bug report -> please search issues before submitting
    - [ ] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

cd 3-Authorization-II/1-call-api/API/AppCreationScripts
./Configure.ps1
cat 3-Authorization-II/1-call-api/API/config.json

json format error: Extra comma
    "credentials": {
        "tenantID": "xxxxxxxxxxxx",
        "clientID": "xxxxxxxxxxxx",
        "audience": "xxxxxxxxxxxx",
    }
### Any log messages given by the failure

>

### Expected/desired behavior

   "credentials": {
        "tenantID": "xxxxxxxxxxxx",
        "clientID": "xxxxxxxxxxxx",
        "audience": "xxxxxxxxxxxx"
    }

### Library version

>

### Browser and version

> Chrome, Edge, Firefox, Safari?

### Mention any other details that might be useful

There are the same problem on 4-1 and 4-2.

repair method:
update UpdateLine function with this code:

```
Function UpdateLine([string] $line, [string] $value)
{
    $delimiter = ''
    $index = $line.IndexOf(',')
    if ( $index -ne -1 )
    {
        $delimiter = ','
    }
    $index = $line.IndexOf('=')
    if ($index -eq -1)
    {
        $index = $line.IndexOf(':')
    }
    if ($index -ige 0)
    {
        $line = $line.Substring(0, $index+1) + " "+'"'+$value+'"'+$delimiter
    }
    return $line
}
```

Thanks! We'll be in touch soon.

**Comment by salman90** [comment]
Hi @sl7xman  , Thank you for your feedback and update, the issue is in the backlog, and we will update the samples as soon as possible.
