### ISSUE TITLE
How to verify ID token from SPA sent backend service?

### ISSUE THREAD

**Issue by chadmott** [Azure-Samples/ms-identity-javascript-tutorial#55]
# Issue

I have the sample application working with your SPA and your API backend. Getting a validated Access bearer token.... all good. 

The thing is that the UI is getting an `id_token` which is great b/c it has certain groups that my user belongs to. I'd like to send this token to my node api layer, and grant certain permissions based on this group association. 

The problem is I have no idea how to verify this ID token.... if I pass it as bearer, it will not validate.... am I thinking about this the wrong way? I would think I would need to validate the ID Token's signature on the node side to make sure that it was a valid token... otherwise someone could forge the ID token (assuming they have a good access token) and get elevated privs. 

I've read https://docs.microsoft.com/en-us/azure/active-directory/develop/id-tokens several times but it is unclear to me how to validate this ID token. Any help/guidance is appreciated to clarify my thinking. 

## This issue is for the sample

```console
    - [ ] 1-1) Sign-in with Azure AD
    - [ ] 1-2) Sign-in with Azure AD B2C
    - [ ] 2-1) Acquire a Token and call Microsoft Graph
    - [X] 3-1) Protect and call a web API on Azure AD
    - [ ] 3-2) Protect and call a web API on Azure AD B2C
    - [ ] 4-1) Call a web API that calls Microsoft Graph on-behalf-of user
    - [ ] 4-2) Call a web API that calls another web API on-behalf-of user
    - [ ]   5) Deploy to Azure Storage and App Service
```

## This issue is for a

```console
    - [ ] bug report -> please search issues before submitting
    - [X] question
    - [ ] feature request
    - [ ] documentation issue or request
```

### Minimal steps to reproduce

>

### Any log messages given by the failure

>

### Expected/desired behavior

A (server side) verified ID token

### Library version

latest

### Browser and version

node (web api), chrome browser

### Mention any other details that might be useful

>

Thanks! We'll be in touch soon.

**Comment by salman90** [comment]
Hi @chadmott,

We don't send the id-token to another application to be validated. The id-token is only meant for the app that acquires it. In this case, you will send the access token to API to validate your permissions. The access token will include the groups that the user belongs to. Please check this sample [single-page application calling Node.js web API using Security Groups to implement Role-Based Access Control for more information](https://github.com/Azure-Samples/ms-identity-javascript-react-tutorial/tree/main/5-AccessControl/2-call-api-groups).
